// Leveled curriculum: Lithuanian -> English, phrase level.
// Two tracks: `dad` (absolute beginner — single words / short phrases) and
// `mom` (a step higher — full useful sentences). Each track is an ordered list
// of themed units; units unlock as the previous one is mastered (see levels.js).
//
// Authoring format below keeps content readable: each card is [lt, en].
// buildCurriculum() turns it into { id, lt, en } records with stable ids so SRS
// state survives edits to neighbouring cards.

const RAW = {
  dad: [
    {
      id: 'dad-greetings',
      title: 'Pasisveikinimai',
      icon: '👋',
      cards: [
        ['Labas', 'Hello'],
        ['Sveiki', 'Hello (to many)'],
        ['Labas rytas', 'Good morning'],
        ['Laba diena', 'Good afternoon'],
        ['Labas vakaras', 'Good evening'],
        ['Labanakt', 'Good night'],
        ['Kaip sekasi?', 'How are you?'],
        ['Gerai, ačiū', "I'm fine, thank you"],
        ['Iki', 'Bye'],
        ['Iki pasimatymo', 'See you later'],
        ['Viso gero', 'Goodbye'],
      ],
    },
    {
      id: 'dad-polite',
      title: 'Mandagūs žodžiai',
      icon: '🙏',
      cards: [
        ['Prašau', 'Please'],
        ['Ačiū', 'Thank you'],
        ['Labai ačiū', 'Thank you very much'],
        ['Nėra už ką', "You're welcome"],
        ['Atsiprašau', 'Excuse me'],
        ['Atleiskite', "I'm sorry"],
        ['Malonu susipažinti', 'Nice to meet you'],
        ['Sveikinu', 'Congratulations'],
        ['Į sveikatą', 'Cheers'],
        ['Prašom', 'Here you are'],
      ],
    },
    {
      id: 'dad-basics',
      title: 'Pagrindai',
      icon: '✅',
      cards: [
        ['Taip', 'Yes'],
        ['Ne', 'No'],
        ['Galbūt', 'Maybe'],
        ['Gerai', 'Okay'],
        ['Nežinau', "I don't know"],
        ['Suprantu', 'I understand'],
        ['Nesuprantu', "I don't understand"],
        ['Aš nekalbu angliškai', "I don't speak English"],
        ['Kalbėkite lėčiau, prašau', 'Please speak slowly'],
        ['Pakartokite, prašau', 'Please repeat'],
        ['Padėkite man, prašau', 'Please help me'],
      ],
    },
    {
      id: 'dad-numbers',
      title: 'Skaičiai',
      icon: '🔢',
      cards: [
        ['nulis', 'zero'],
        ['vienas', 'one'],
        ['du', 'two'],
        ['trys', 'three'],
        ['keturi', 'four'],
        ['penki', 'five'],
        ['šeši', 'six'],
        ['septyni', 'seven'],
        ['aštuoni', 'eight'],
        ['devyni', 'nine'],
        ['dešimt', 'ten'],
      ],
    },
    {
      id: 'dad-family',
      title: 'Šeima',
      icon: '👨‍👩‍👧',
      cards: [
        ['šeima', 'family'],
        ['mama', 'mother'],
        ['tėtis', 'father'],
        ['sūnus', 'son'],
        ['dukra', 'daughter'],
        ['brolis', 'brother'],
        ['sesuo', 'sister'],
        ['žmona', 'wife'],
        ['vyras', 'husband'],
        ['vaikas', 'child'],
        ['senelė', 'grandmother'],
        ['senelis', 'grandfather'],
      ],
    },
    {
      id: 'dad-food',
      title: 'Maistas ir gėrimai',
      icon: '🍽️',
      cards: [
        ['vanduo', 'water'],
        ['duona', 'bread'],
        ['pienas', 'milk'],
        ['kava', 'coffee'],
        ['arbata', 'tea'],
        ['sūris', 'cheese'],
        ['mėsa', 'meat'],
        ['vaisiai', 'fruit'],
        ['daržovės', 'vegetables'],
        ['alus', 'beer'],
        ['valgyti', 'to eat'],
        ['gerti', 'to drink'],
      ],
    },
    {
      id: 'dad-shop',
      title: 'Parduotuvėje',
      icon: '🛒',
      cards: [
        ['parduotuvė', 'shop'],
        ['pinigai', 'money'],
        ['Kiek kainuoja?', 'How much is it?'],
        ['brangu', 'expensive'],
        ['pigu', 'cheap'],
        ['Aš noriu šito', 'I want this'],
        ['Ar turite...?', 'Do you have...?'],
        ['Aš ieškau...', 'I am looking for...'],
        ['kvitas', 'receipt'],
        ['maišelis', 'bag'],
      ],
    },
    {
      id: 'dad-time',
      title: 'Laikas ir dienos',
      icon: '🕐',
      cards: [
        ['šiandien', 'today'],
        ['rytoj', 'tomorrow'],
        ['vakar', 'yesterday'],
        ['diena', 'day'],
        ['naktis', 'night'],
        ['savaitė', 'week'],
        ['valanda', 'hour'],
        ['dabar', 'now'],
        ['vėliau', 'later'],
        ['Kiek valandų?', 'What time is it?'],
        ['savaitgalis', 'weekend'],
      ],
    },
    {
      id: 'dad-health',
      title: 'Kūnas ir savijauta',
      icon: '🩺',
      cards: [
        ['Man skauda', 'It hurts'],
        ['galva', 'head'],
        ['pilvas', 'stomach'],
        ['Man bloga', 'I feel sick'],
        ['Aš pavargęs', 'I am tired'],
        ['Aš sergu', 'I am ill'],
        ['ligoninė', 'hospital'],
        ['vaistai', 'medicine'],
        ['gydytojas', 'doctor'],
        ['Man reikia pagalbos', 'I need help'],
        ['Skambinkite gydytojui', 'Call a doctor'],
      ],
    },
    {
      id: 'dad-directions',
      title: 'Kelias ir vietos',
      icon: '🧭',
      cards: [
        ['kur', 'where'],
        ['čia', 'here'],
        ['ten', 'there'],
        ['kairė', 'left'],
        ['dešinė', 'right'],
        ['tiesiai', 'straight ahead'],
        ['toli', 'far'],
        ['namai', 'home'],
        ['gatvė', 'street'],
        ['miestas', 'city'],
        ['Kur yra tualetas?', 'Where is the toilet?'],
        ['Aš pasiklydau', 'I am lost'],
      ],
    },
  ],

  mom: [
    {
      id: 'mom-smalltalk',
      title: 'Pokalbio pradžia',
      icon: '💬',
      cards: [
        ['Labas, malonu tave matyti', 'Hi, nice to see you'],
        ['Kaip tau sekasi šiandien?', 'How are you doing today?'],
        ['Man viskas gerai, ačiū', "I'm doing well, thank you"],
        ['O kaip tu?', 'And how about you?'],
        ['Seniai nesimatėme', 'Long time no see'],
        ['Ką veiki?', 'What are you up to?'],
        ['Gražus oras šiandien', 'The weather is nice today'],
        ['Smagu su tavimi pasikalbėti', "It's nice to talk with you"],
        ['Turiu eiti, iki', 'I have to go, bye'],
        ['Geros dienos!', 'Have a nice day!'],
        ['Pasimatysime vėliau', 'See you later'],
      ],
    },
    {
      id: 'mom-aboutme',
      title: 'Apie save',
      icon: '🙋',
      cards: [
        ['Mano vardas yra...', 'My name is...'],
        ['Aš esu iš Lietuvos', 'I am from Lithuania'],
        ['Aš gyvenu Vilniuje', 'I live in Vilnius'],
        ['Aš mokausi anglų kalbos', 'I am learning English'],
        ['Aš kalbu šiek tiek angliškai', 'I speak a little English'],
        ['Aš nesuprantu, atsiprašau', "I don't understand, sorry"],
        ['Ar galite pakartoti?', 'Could you repeat that?'],
        ['Kalbėkite lėčiau, prašau', 'Please speak more slowly'],
        ['Ką tai reiškia?', 'What does that mean?'],
        ['Kaip tai pasakyti angliškai?', 'How do you say this in English?'],
        ['Aš turiu du vaikus', 'I have two children'],
      ],
    },
    {
      id: 'mom-shopping',
      title: 'Parduotuvėje',
      icon: '🛍️',
      cards: [
        ['Kiek tai kainuoja?', 'How much does this cost?'],
        ['Aš tik apsidairau, ačiū', "I'm just looking, thank you"],
        ['Ar galiu tai pasimatuoti?', 'Can I try this on?'],
        ['Ar turite kitą dydį?', 'Do you have another size?'],
        ['Kur yra kasa?', 'Where is the checkout?'],
        ['Ar galiu mokėti kortele?', 'Can I pay by card?'],
        ['Ar priimate grynuosius?', 'Do you take cash?'],
        ['Prašau, duokite kvitą', 'Can I have the receipt, please?'],
        ['Tai per brangu man', 'That is too expensive for me'],
        ['Aš tai paimsiu', 'I will take it'],
        ['Ar galite man padėti?', 'Can you help me?'],
      ],
    },
    {
      id: 'mom-restaurant',
      title: 'Restorane',
      icon: '🍴',
      cards: [
        ['Stalą dviem, prašau', 'A table for two, please'],
        ['Ar galiu pamatyti meniu?', 'Can I see the menu?'],
        ['Ką rekomenduojate?', 'What do you recommend?'],
        ['Aš norėčiau šito', 'I would like this one'],
        ['Stiklinę vandens, prašau', 'A glass of water, please'],
        ['Tai labai skanu', 'This is very tasty'],
        ['Sąskaitą, prašau', 'The bill, please'],
        ['Ar aptarnavimas įskaičiuotas?', 'Is the service included?'],
        ['Aš esu vegetarė', 'I am a vegetarian'],
        ['Be cukraus, prašau', 'Without sugar, please'],
        ['Viskas buvo puiku', 'Everything was great'],
      ],
    },
    {
      id: 'mom-doctor',
      title: 'Pas gydytoją',
      icon: '🩺',
      cards: [
        ['Man reikia susitarti dėl vizito', 'I need to make an appointment'],
        ['Aš blogai jaučiuosi', 'I am not feeling well'],
        ['Man skauda galvą', 'I have a headache'],
        ['Man skauda gerklę', 'I have a sore throat'],
        ['Aš turiu temperatūrą', 'I have a fever'],
        ['Tai prasidėjo vakar', 'It started yesterday'],
        ['Ar galite man kažką paskirti?', 'Can you prescribe me something?'],
        ['Aš geriu šiuos vaistus', 'I am taking this medicine'],
        ['Aš esu alergiška penicilinui', 'I am allergic to penicillin'],
        ['Kur yra artimiausia vaistinė?', 'Where is the nearest pharmacy?'],
        ['Ačiū už pagalbą', 'Thank you for your help'],
      ],
    },
    {
      id: 'mom-travel',
      title: 'Kelionės ir kryptys',
      icon: '🧭',
      cards: [
        ['Atsiprašau, kaip nueiti į...?', 'Excuse me, how do I get to...?'],
        ['Ar tai toli nuo čia?', 'Is it far from here?'],
        ['Aš ieškau šio adreso', 'I am looking for this address'],
        ['Pasukite į kairę prie šviesoforo', 'Turn left at the traffic lights'],
        ['Eikite tiesiai', 'Go straight ahead'],
        ['Kur yra autobusų stotis?', 'Where is the bus station?'],
        ['Kada atvyksta traukinys?', 'When does the train arrive?'],
        ['Vieną bilietą, prašau', 'One ticket, please'],
        ['Ar šis autobusas važiuoja į centrą?', 'Does this bus go to the centre?'],
        ['Aš pasiklydau', 'I am lost'],
        ['Ar galite parodyti žemėlapyje?', 'Can you show me on the map?'],
      ],
    },
    {
      id: 'mom-phone',
      title: 'Telefonas ir susitarimai',
      icon: '📞',
      cards: [
        ['Labas, ar galiu kalbėti su...?', 'Hello, can I speak to...?'],
        ['Kas skambina?', 'Who is calling?'],
        ['Ar galite paskambinti vėliau?', 'Can you call back later?'],
        ['Aš jums perskambinsiu', 'I will call you back'],
        ['Susitarkime susitikti rytoj', "Let's arrange to meet tomorrow"],
        ['Kuriuo laiku tau patogu?', 'What time works for you?'],
        ['Ar tau tinka pirmadienis?', 'Does Monday work for you?'],
        ['Aš šiek tiek vėluosiu', 'I will be a little late'],
        ['Atsiprašau, suklydau numeriu', 'Sorry, wrong number'],
        ['Ar gali atsiųsti man žinutę?', 'Can you send me a message?'],
        ['Pasimatysime tada', 'See you then'],
      ],
    },
    {
      id: 'mom-home',
      title: 'Šeima ir kasdienybė',
      icon: '🏡',
      cards: [
        ['Šiandien turiu daug darbų', 'I have a lot to do today'],
        ['Reikia nupirkti maisto', 'I need to buy some food'],
        ['Aš gaminu vakarienę', 'I am cooking dinner'],
        ['Vaikai eina į mokyklą', 'The children go to school'],
        ['Mano vyras dirba', 'My husband is working'],
        ['Vakare einame pasivaikščioti', 'In the evening we go for a walk'],
        ['Savaitgalį ilsimės', 'At the weekend we relax'],
        ['Aš tvarkau namus', 'I am cleaning the house'],
        ['Ar gali man padėti?', 'Can you help me?'],
        ['Aš pavargau', 'I am tired'],
        ['Eikime miegoti', "Let's go to sleep"],
      ],
    },
    {
      id: 'mom-feelings',
      title: 'Jausmai ir nuomonė',
      icon: '💭',
      cards: [
        ['Aš manau, kad tai gera mintis', "I think that's a good idea"],
        ['Man tai labai patinka', 'I really like it'],
        ['Aš su tavimi sutinku', 'I agree with you'],
        ['Aš nesutinku', "I don't agree"],
        ['Man atrodo, kad...', 'It seems to me that...'],
        ['Aš nesu tikra', 'I am not sure'],
        ['Tai mane džiugina', 'That makes me happy'],
        ['Aš dėl to nerimauju', 'I am worried about it'],
        ['Nesijaudink, viskas bus gerai', "Don't worry, it will be fine"],
        ['Tai puiki naujiena', 'That is great news'],
        ['Aš tavimi didžiuojuosi', 'I am proud of you'],
      ],
    },
    {
      id: 'mom-work',
      title: 'Tvarkymasis',
      icon: '🗂️',
      cards: [
        ['Ar galiu jums padėti?', 'Can I help you?'],
        ['Vieną akimirką, prašau', 'One moment, please'],
        ['Aš nesu tikra, leiskite patikrinti', "I'm not sure, let me check"],
        ['Ar galite tai parašyti?', 'Could you write that down?'],
        ['Aš atsiųsiu jums el. laišką', 'I will send you an email'],
        ['Kada tai bus paruošta?', 'When will it be ready?'],
        ['Man reikia pagalbos su tuo', 'I need help with this'],
        ['Ačiū, kad palaukėte', 'Thank you for waiting'],
        ['Atsiprašau už vėlavimą', 'Sorry for the delay'],
        ['Ar galime susitikti vėliau?', 'Can we meet later?'],
        ['Puiku, susitarėme', "Great, it's settled"],
      ],
    },
  ],
};

function buildCurriculum() {
  const out = {};
  for (const track of Object.keys(RAW)) {
    out[track] = RAW[track].map((unit) => ({
      id: unit.id,
      title: unit.title,
      icon: unit.icon,
      custom: false,
      cards: unit.cards.map(([lt, en], i) => ({
        id: `${unit.id}-${i + 1}`,
        lt,
        en,
      })),
    }));
  }
  return out;
}

export const CURRICULUM = buildCurriculum();

export const PROFILES = {
  dad: { id: 'dad', label: 'Tėtis', emoji: '👨' },
  mom: { id: 'mom', label: 'Mama', emoji: '👩' },
};
